USE [master]
GO

/****** Object:  Database [laboratorio]    Script Date: 04/29/2013 19:21:35 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'laboratorio')
DROP DATABASE [laboratorio]
GO

USE [master]
GO

/****** Object:  Database [laboratorio]    Script Date: 04/29/2013 19:21:35 ******/
CREATE DATABASE [laboratorio] ON  PRIMARY 
( NAME = N'laboratorio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.ERIK_SQL\MSSQL\DATA\laboratorio.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'laboratorio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.ERIK_SQL\MSSQL\DATA\laboratorio_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [laboratorio] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [laboratorio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [laboratorio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [laboratorio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [laboratorio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [laboratorio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [laboratorio] SET ARITHABORT OFF 
GO

ALTER DATABASE [laboratorio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [laboratorio] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [laboratorio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [laboratorio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [laboratorio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [laboratorio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [laboratorio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [laboratorio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [laboratorio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [laboratorio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [laboratorio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [laboratorio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [laboratorio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [laboratorio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [laboratorio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [laboratorio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [laboratorio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [laboratorio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [laboratorio] SET  READ_WRITE 
GO

ALTER DATABASE [laboratorio] SET RECOVERY FULL 
GO

ALTER DATABASE [laboratorio] SET  MULTI_USER 
GO

ALTER DATABASE [laboratorio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [laboratorio] SET DB_CHAINING OFF 
GO

